# Generated by Django 3.0 on 2021-04-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.FloatField(choices=[('Indoor', 'ndoor'), ('Out Door', 'Out Door')], null=True),
        ),
    ]
