# Generated by Django 3.0 on 2021-04-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210418_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.FloatField(choices=[('Indoor', 'Indoor'), ('Out Door', 'Out Door')], null=True),
        ),
    ]
