# Generated by Django 3.0 on 2021-04-18 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210418_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Customer'),
        ),
    ]
